### ISSUE TITLE
Draft SFA Documentation

### ISSUE THREAD

**Issue by jerielizabeth** [Omeka-External/sfa-theme#2]
New issue for the draft of the theme documentation.

One additional question I have for @kalbers and @sharonmleon is what is the primary way we expect these users to be adding items? I will provide documentation for all, but in terms of where to put the greatest emphasis, do we expect them to use primarily the ohms import (xml file), CSV import, or the Omeka interface for individual items? (or another option that I should prep for?)

Thanks!

**Comment by kalbers** [comment]
I'm not entirely sure, but can ping them if that would be helpful. I believe since we are going to be installing Dropbox and CSV Import as well as the OHMS stuff, there's a chance they will be using all three.

**Comment by jerielizabeth** [comment]
I have a draft of the documentation in a google doc. I can share a google link on request.

I am a bit stuck on the CSV Import part, mostly in needing an example CSV. Are we assuming an import of Oral History items with OHMS metadata fields via CSV? Or would a more generic item structure work fine?

**Comment by kalbers** [comment]
Hi Jeri,

I pinged them about this this week and have a call set up for Thursday. I should be able to give you a definitive answer then.

In the meantime, I think that covering a straight CSV import would be fine. We can always drop in an additional line about mapping the OHMS stuff afterwards, if needed.

**Comment by jerielizabeth** [comment]
I made a two item CSV file with content from the Mason libraries for demo purposes. It is oral history but does not use the OHMS fields.
